import os
import glob
import math
import argparse
import re
from PIL import Image

def create_grids(image_dir, search_pattern_string="L2L3Res_Fit_eta_*.png", cols=5, rows=5, prefix="Grid_Summary_Part"):
    # Find all the individual fit plots generated by the C++ script
    search_pattern = os.path.join(image_dir, search_pattern_string)
    images = glob.glob(search_pattern)
    
    # Sort them based on your preference. 
    # Define a key function for "natural sorting" (human sorting)
    # It splits the filename into text and integer parts and sorts numbers numerically
    def natural_sort_key(s):
        return [int(text) if text.isdigit() else text.lower() for text in re.split(r'(\d+)', s)]

    # Sort them using the natural sort key
    images.sort(key=natural_sort_key)

    if not images:
        print(f"No images found matching '{search_pattern_string}' in {image_dir}")
        return

    # Calculate dimensions
    max_per_grid = cols * rows
    sample_img = Image.open(images[0])
    img_w, img_h = sample_img.size

    # Split into chunks of (cols x rows) (or fewer)
    chunks = [images[i:i + max_per_grid] for i in range(0, len(images), max_per_grid)]

    for chunk_idx, chunk in enumerate(chunks):
        # Dynamically size the output canvas if the chunk is smaller than (cols x rows)
        current_rows = math.ceil(len(chunk) / cols)
        grid_w = cols * img_w
        grid_h = current_rows * img_h
        
        grid_img = Image.new('RGB', (grid_w, grid_h), color=(255, 255, 255))

        for idx, img_path in enumerate(chunk):
            col = idx % cols
            row = idx // cols
            img = Image.open(img_path)
            grid_img.paste(img, (col * img_w, row * img_h))

        # Use the custom prefix for the filename
        output_file = os.path.join(image_dir, f"{prefix}{chunk_idx + 1}.png")
        grid_img.save(output_file)
        print(f"Saved {output_file} with {len(chunk)} plots.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Combine individual ROOT plots into structured image grids.")
    
    # Positional argument (required)
    parser.add_argument("dir", type=str, help="Target directory containing the input images.")
    
    # Optional arguments
    parser.add_argument("-n", "--name", type=str, default="Grid_Summary_Part", help="Prefix for the output files (default: Grid_Summary_Part)")
    parser.add_argument("-c", "--cols", type=int, default=5, help="Number of columns per grid (default: 5)")
    parser.add_argument("-r", "--rows", type=int, default=5, help="Number of rows per grid (default: 5)")
    parser.add_argument("-p", "--pattern", type=str, default="L2L3Res_Fit_eta_*.png", help="File matching pattern (default: L2L3Res_Fit_eta_*.png)")

    args = parser.parse_args()

    # Run the function with the parsed arguments
    create_grids(args.dir, search_pattern_string=args.pattern, cols=args.cols, rows=args.rows, prefix=args.name)
    