import os
import glob
import math
from PIL import Image

def create_grids(image_dir, cols=4, rows=4):
    # Find all the individual fit plots generated by the C++ script
    search_pattern = os.path.join(image_dir, "L2L3Res_Fit_eta_*.png")
    images = glob.glob(search_pattern)
    
    # Sort them based on your preference. 
    # By default, alphabetical sorting of "+02.500" strings sorts them perfectly from most negative to most positive.
    images.sort()

    if not images:
        print("No images found in", image_dir)
        return

    # Calculate dimensions
    max_per_grid = cols * rows
    sample_img = Image.open(images[0])
    img_w, img_h = sample_img.size

    # Split into chunks of (cols x rows) (or fewer)
    chunks = [images[i:i + max_per_grid] for i in range(0, len(images), max_per_grid)]

    for chunk_idx, chunk in enumerate(chunks):
        # Dynamically size the output canvas if the chunk is smaller than (cols x rows)
        current_rows = math.ceil(len(chunk) / cols)
        grid_w = cols * img_w
        grid_h = current_rows * img_h
        
        grid_img = Image.new('RGB', (grid_w, grid_h), color=(255, 255, 255))

        for idx, img_path in enumerate(chunk):
            col = idx % cols
            row = idx // cols
            img = Image.open(img_path)
            grid_img.paste(img, (col * img_w, row * img_h))

        output_path = os.path.join(image_dir, f"Grid_Summary_Part{chunk_idx + 1}.png")
        grid_img.save(output_path)
        print(f"Saved {output_path} with {len(chunk)} plots.")

# --- Run the function ---
# Replace this path with the path you want to save the plots to
target_directory = "/eos/user/t/tchatzis/php-plots/JEC4Prompt/testFits/2025G/fits/"
create_grids(target_directory)
